ci:
  - .github/workflows/**
  - .github/labeler.yml
  - .actrc
  - .pre-commit-config.yaml

protocol:
  - crates/lib/src/protocols/**

game:
  - crates/lib/src/games/**

cli:
  - crates/cli/**

crate:
  - Cargo.toml
  - Cargo.lock
