ci:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**'
      - .github/labeler.yml
      - .actrc
      - .pre-commit-config.yaml

protocol:
- all:
  - changed-files:
    - any-glob-to-any-file: crates/lib/src/protocols/**

game:
- all:
  - changed-files:
    - any-glob-to-any-file: crates/lib/src/games/**

cli:
- all:
  - changed-files:
    - any-glob-to-any-file: crates/cli/**

crate:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - Cargo.toml
      - 'crates/**/Cargo.toml'
      - 'crates/**/Cargo.lock'
