[package]
name = "gamedig"
version = "0.2.1"
edition = "2021"
authors = ["CosminPerRam [https://github.com/CosminPerRam]", "node-GameDig contributors [https://github.com/gamedig/node-gamedig/contributors]"]
license = "MIT"
description = "Check out servers with this."
homepage = "https://github.com/gamedig/rust-gamedig"
documentation = "https://docs.rs/gamedig/latest/gamedig/"
repository = "https://github.com/gamedig/rust-gamedig"
readme = "README.md"
keywords = ["server", "query", "game", "check", "status"]
rust-version = "1.56.1"

[features]
no_games = []

[dependencies]
byteorder = "1.4.3"

bzip2-rs = "0.1.2" # for compression
crc32fast = "1.3.2"

serde_json = "1.0.91" # json to structs
