[package]
name = "gamedig"
version = "0.2.0"
edition = "2021"
authors = ["CosminPerRam [cosmin.p@live.com]", "node-GameDig [https://github.com/gamedig/node-gamedig]"]
license = "MIT"
description = "Check out servers with this."
homepage = "https://github.com/CosminPerRam/rust-gamedig"
documentation = "https://docs.rs/gamedig/latest/gamedig/"
repository = "https://github.com/CosminPerRam/rust-gamedig"
readme = "README.md"
keywords = ["server", "query", "game", "check", "status"]
rust-version = "1.56.1"

[dependencies]
bzip2-rs = "0.1.2" # for compression
crc32fast = "1.3.2"

serde_json = "1.0.91" # json to structs
