name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_first:
    name: "Build, check, and test with all features"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "cargo-deps"
          cache-targets: false
      - name: Run Build
        run: cargo build --verbose --bins --lib --examples --all-features
      - name: Run Clippy
        run: cargo clippy --verbose --bins --lib --examples --all-features
      - name: Run Tests
        run: cargo test --verbose --bins --lib --examples --all-features
  build:
    runs-on: ubuntu-latest
    needs: [ "build_first" ]
    strategy:
      fail-fast: false
      matrix:
        include:
          - build_type: ""
            build_name: "Default"
          - build_type: "--no-default-features"
            build_name: "No features"
          - build_type: "--no-default-features --features games"
            build_name: "Games no services"
          - build_type: "--no-default-features --features services"
            build_name: "Services no games"
          - build_type: "--no-default-features --features game_defs"
            build_name: "Game defs"
    name: "Build ${{ matrix.build_name }}"
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "cargo-deps"
          cache-targets: false
      - name: Run Build
        run: cargo build --verbose --bins --lib ${{ matrix.build_type }}
  build_msrv:
    name: "Build using MSRV"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Install MSRV
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.60.0
          override: true
      - name: Run MSRV
        run: cargo build
  formatting:
    name: "Check code formatting"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Install Formatting nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-07-09
          components: rustfmt
          override: true
      - name: Run Formatting check
        run: cargo fmt --check --verbose
